// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQswGgXMiAmTkZQpMzgkRw08aCtA9Gvps',
    appId: '1:262580943540:web:c5b87e249eb38c0ccdf5e1',
    messagingSenderId: '262580943540',
    projectId: 'offline-attendence',
    authDomain: 'offline-attendence.firebaseapp.com',
    storageBucket: 'offline-attendence.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJO_Y7zPjvBkge2krxHVO_yXiogHSweHc',
    appId: '1:262580943540:android:b0f021f0588e6801cdf5e1',
    messagingSenderId: '262580943540',
    projectId: 'offline-attendence',
    storageBucket: 'offline-attendence.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2nfjwAlHjmMs0iit64E2EuICjHBbzvKA',
    appId: '1:262580943540:ios:fc49907ff67ee525cdf5e1',
    messagingSenderId: '262580943540',
    projectId: 'offline-attendence',
    storageBucket: 'offline-attendence.appspot.com',
    iosBundleId: 'com.example.offlineAttendence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQswGgXMiAmTkZQpMzgkRw08aCtA9Gvps',
    appId: '1:262580943540:web:77444078fb1b49d8cdf5e1',
    messagingSenderId: '262580943540',
    projectId: 'offline-attendence',
    authDomain: 'offline-attendence.firebaseapp.com',
    storageBucket: 'offline-attendence.appspot.com',
  );
}
